config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  # 検索ボタンが押された時にsearchesコントローラーのsearchアクションが実行される
  get 'search' => 'searches#search'

  resources :chats, only: [:show, :create]

  resources :users do
   resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
    @book_comment = BookComment.new
    # redirect_to request.referer
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new
    # redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
 <%= f.text_area :comment, size:"90x5" %>
 <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_index.html.erb
 <table>
  <tbody>
    <% book.book_comments.each do |book_comment| %>
    <tr>

      <td>
        <%= link_to user_path(book_comment.user) do %>
          <%= image_tag book_comment.user.get_profile_image, size: "100x100" %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <td>
      <% if book_comment.user == current_user %>
      <div class="comment-delete">
       <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger btn-sm" %>
      </div>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
 </table>

app/views/book_comments/create.js.erb
$("#comments-index").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#comments-form").html("<%= j(render 'book_comments/form', book: @book, book_comment: @book_comment) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');

app/views/book_comments/destroy.js.erb
$("#comments-index").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#comments-form").html("<%= j(render 'book_comments/form', book: @book, book_comment: @book_comment) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');