config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  # 検索ボタンが押された時にsearchesコントローラーのsearchアクションが実行される
  get 'search' => 'searches#search'

  resources :chats, only: [:show, :create]

  resources :users do
   resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # フォローするユーザーに結びついている
  belongs_to :followed, class_name: "User"

  # フォローされるユーザーに結びついている
  belongs_to :follower, class_name: "User"

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
 
  def create
    following = current_user.relationships.build(follower_id: params[:user_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    following.destroy
    redirect_to request.referrer || root_path
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if user.followed_by?(current_user) %>
  <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-info" %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success" %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.present? %>
  <%= render 'follow', user: @user, users: @users %>
<% else %>
  ユーザーはいません
<% end %>

app/views/relationships/follows.html.erb
<h2>Follow Users</h2>
<% if @users.present? %>
  <%= render 'follow', user: @user, users: @users %>
<% else %>
  ユーザーはいません
<% end %>