config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  # 検索ボタンが押された時にsearchesコントローラーのsearchアクションが実行される
  get 'search' => 'searches#search'

  resources :chats, only: [:show, :create]

  resources :users do
   resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # フォローをする側からのhas_many、自分がフォローしている人の一覧を持ってくる
  has_many :relationships, foreign_key: :followed_id, dependent: :destroy
  has_many :follows, through: :relationships, source: :follower


  # フォローされた側からのhas_many、自分をフォローしている人の一覧を持ってくる
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :followed

  # DM機能
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  # 閲覧数のカウント
  has_many :view_counts, dependent: :destroy


  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50}


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # (user)←この引数に渡されたユーザーにフォローされているか否かのアクション
  def followed_by?(user)
    reverse_of_relationships.find_by(followed_id: user.id).present?
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match" # 完全一致
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"  # 前方一致のため後ろに%
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match" # 後方一致のため前に%
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match" # 部分一致のため前後に%
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user)
   else
     render :edit
   end
  end

  # このユーザーがフォローしている人全員を取得するアクション
  def follows
    user = User.find(params[:id])
    @users = user.follows
  end

  # このユーザーをフォローしている全員を取得するアクション
  def followers
    user = User.find(params[:id])
    @users = user.followers
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%= user.relationships.count %></td>
        <td>フォロワー数<%= user.reverse_of_relationships.count %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  <tr>
	  <th>follows</th>
	  <th>
        <%= link_to follows_user_path(user) do %>
          <%= user.relationships.count %>
        <% end %>
      </th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th>
        <%= link_to followers_user_path(user) do %>
          <%= user.reverse_of_relationships.count %>
        <% end %>
	  </th>
  </tr>
  </table>

　<div class='row'>
    <% if current_user != user %>
      <td><%= render "relationships/btn", user: user %></td>
    <% else %>
       <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
         <i class="fas fa-user-cog"></i>
       <% end %>
    <% end %>

    <% if current_user != user && current_user.followed_by?(user) && user.followed_by?(current_user) %>
      <%= link_to 'chatを始める', chat_path(@user.id), class: "ml-3" %>
      <% end %>
  </div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'info', user: current_user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'layouts/errors', obj: @book %>
          <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
       <h2>Users</h2>
         <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>